### ISSUE TITLE
CMake does not find MySQL Connector C 32-bit on 64-bit system

### ISSUE THREAD

**Issue by iwbnwif** [mtangoo/wxDatabase#10]
On Windows 10 (64-bit):

The CMake FindMySQL.cmake module only looks in C:\Program Files and not C:\Program Files (x86) for the MySQL libraries.

**Comment by mtangoo** [comment]
Thanks for the not. I use MariaDB and its a little bit different. I will add that directory in new commit.
If you have time, can you make a PR?
Thanks again for your time

**Comment by iwbnwif** [comment]
Sorry for not knowing, but what is a PR?

**Comment by mtangoo** [comment]
Its [Pull Request](https://help.github.com/articles/using-pull-requests/)
Basically you:
1. fork repo
2. make changes (fix a bug et al)
3. Push changes to your fork
4. Make PR to original repo

**Comment by iwbnwif** [comment]
Ah, sorry I am new(ish) to Git. I will try this later today.

**Comment by mtangoo** [comment]
Let me know if you face any issue :)
