### ISSUE TITLE
Online docs missing?

### ISSUE THREAD

**Issue by ghaberek** [mtangoo/wxDatabase#19]
README.md states that documentation can be found online:

> wxDatabase documentation is built with [Doxygen](http://doxygen.org). Download the latest version and follow the procedure in the next paragraph to build API documentation. _**You can view documentation on line at [mtangoo.github.io](http://mtangoo.github.io).**_

However, that page simply says **Hello World** and nothing more.

**Comment by mtangoo** [comment]
Hi, 
I have not yet pushed the docs online. Am still formating it, so meanwhile you can just generate them using doxygen.  I will try to find time and push them up

**Comment by mtangoo** [comment]
I uploaded it there.
Enjoy!
