### ISSUE TITLE
Add Support for ODBC in CMake

### ISSUE THREAD

**Issue by mtangoo** [mtangoo/wxDatabase#5]
Add ODBC to CMake Build

**Comment by mtangoo** [comment]
@patlkli @manyleaves Do we have a database that is not covered (and hence require ODBC)?
I was looking at the list, we have almost every major DB covered.

**Comment by patlkli** [comment]
I would not drop ODBC support anyway. The ODBC part of wxDatabase is pretty much working as it is right now, so I don't see a point in arbitrarily dropping it.

**Comment by mtangoo** [comment]
:+1:
